numpy practies

 Checking the numpy version(np.__version__)

In [74]:
import numpy as np

print(np.__version__)# Checking the numpy version

1.24.3


array in numpy all dimentions (np.array)

In [5]:
import numpy as np

print(np.array(20)) # 0 Dimentation array 

print(np.array([1,2])) # 1 Dimentation array

print(np.array([[[1,2],[3,4]],[[8,6],[9,3]]])) # 2 Dimentation array

print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])) # 3 Dimentation array

print(np.array([[[1,2,3],[4,5,6]]],ndmin=4))  # 4 Dimentation array

print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]],ndmin=5))  # 5 Dimentation array ( creating more than 3D array)

20
[1 2]
[[[1 2]
  [3 4]]

 [[8 6]
  [9 3]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
[[[[1 2 3]
   [4 5 6]]]]
[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [11 12 13]]]]]


check Dimensions (np.ndim),(np.array)

In [8]:
#Check the  Dimentation
a=np.array(23)
b=np.array([[1,2],[3,4]])
d=np.array([[1,2],[3,4]],ndmin=10)
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(d))

0
2
10


Checking Shape of the array

In [1]:
import numpy as np
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([1,2],ndmin=4)
print(arr2.shape)
print(np.shape(arr1))
sh1=np.array([[[1,2,3],[4,5,6]]],ndmin=4)
print(np.shape(sh1))

(1, 1, 1, 2)
(2, 3)
(1, 1, 2, 3)


easily create an array filled with 0’s:

In [11]:
import numpy as np

print(np.zeros(9)) # create  an array filled with 0's 

print(np.zeros([1,10,4])) # create  an array filled with 0's 

print(np.ones([1,10,6])) # create  an array filled with 1's 

print(np.ones(9)) # create  an array filled with 1's 

print(np.arange(6)) # create an  array with a range of element

print(np.arange(1,10,2)) # create an  array with a range of element

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5]
[1 3 5 7 9]


Sorting arrays

In [24]:
import numpy as np

print(np.sort((2,4,1,5,3,6,9,8,6,7,))) # numbers

print(np.sort(("b","a","A","g","y","N","u"))) # alpabets

print(np.sort([[5,2,3],[9,5,2]])) #2 D array



[1 2 3 4 5 6 6 7 8 9]
['A' 'N' 'a' 'b' 'g' 'u' 'y']
[[2 3 5]
 [2 5 9]]


21/06/2023

access an array element by referring to its index number.

In [114]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8])

print(arr[-8:-4])


[1 2 3 4]


In [167]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print("value :",arr[0, 1, 2])

data=np.array([ [[52,65,85],[10,20,30]],[[40,50,60],[70,80,90]] ])
print(data)
print("value :",data[0,0,0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
value : 6
[[[52 65 85]
  [10 20 30]]

 [[40 50 60]
  [70 80 90]]]
value : 52


In [169]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print("value :",arr[1:7:2])

[1 2 3 4 5 6 7 8]
value : [2 4 6]


In [177]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print("value :",arr1[1,0:3])

value : [5 6 7]


In [198]:
arr=np.array([1,2,3,4,5,6,7,4,8,])
x=(np.where(arr%3==1))
z=(np.where(arr%2==0))
print(x)
print(z) # using this condition divisabel by which number divisabel by 2 give the those index number

y=(np.where(arr==4))
print(y)# using this condition give the repeated value of 4




(array([0, 3, 6, 7], dtype=int64),)
(array([1, 3, 5, 7, 8], dtype=int64),)
(array([3, 7], dtype=int64),)


Search sorted array

In [213]:
arr2=np.array([1,2,3,5,6,7])
print(np.searchsorted(arr,4))

print(np.searchsorted([1,2,3,5,6,7],8,side="right"))

print(np.searchsorted([1,2,3,5,6,7],[-2,10,5,-4]))


3
6
[0 6 3 0]


In [244]:
import numpy as np
arr2=np.array([1,2,3,5,4,6,7,8,9,10,11,12])
newarr=arr2.reshape(4,3)
print(newarr)


arr1=np.array([[1,2,3,4],[5,6,7,8]])
x=arr1.reshape(-1)
print(x)

[[ 1  2  3]
 [ 5  4  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6 7 8]


Filtering array

In [6]:
import numpy as np 
arr1=np.array([10,20,30,40,50,])
b=[True,False,True,False,True]
newarr=arr1[b]
print(newarr)

[10 30 50]


Filtering array using lamda function

In [16]:
import numpy as np

ar=np.array([12,3,4,5,6,7,8,9,10])
#Filtering the only odd number using lamda function
result=filter(lambda x:x%2!=0,ar)
print(list(result)) 
#Filtering the only even number using lamda function
result=filter(lambda x:x%2==0,ar)
print(list(result))

[3, 5, 7, 9]
[12, 4, 6, 8, 10]


In [15]:
import numpy as np

ar=np.array([12,3,4,5,6,7,8,9,10])
#Filtering the only odd number using lamda function
result=filter(lambda x:x%2!=0,ar)
print(set(result))
#Filtering the only even number using lamda function
result=filter(lambda x:x%2==0,ar)
print(set(result))

{9, 3, 5, 7}
{4, 6, 8, 10, 12}


Concatenate()


In [24]:
import numpy as np

a=np.arange(6).reshape(2,3)
print(a)

b=np.arange(7,17).reshape(2,5)
print(b)

np.concatenate((a,b))



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 7  8  9 10 11]
 [12 13 14 15 16]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [109]:
import numpy as np


a=np.arange(10).reshape(2,5)
print("a:",a)


b=np.arange(7,17).reshape(2,5)
print("b :",b)

x=np.arange(1,20,2).reshape(2,5)
print("x",x)


y=np.arange(21,40,2).reshape(2,5)
print("y",y)

np.concatenate((a,b,x,y))




a: [[0 1 2 3 4]
 [5 6 7 8 9]]
b : [[ 7  8  9 10 11]
 [12 13 14 15 16]]
x [[ 1  3  5  7  9]
 [11 13 15 17 19]]
y [[21 23 25 27 29]
 [31 33 35 37 39]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [21]:

a=np.arange(6).reshape(2,3)
print("a:",a)


b=np.arange(7,13).reshape(2,3)
print("b :",b)

np.concatenate((a,b),axis=1)



a: [[0 1 2]
 [3 4 5]]
b : [[ 7  8  9]
 [10 11 12]]


array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [103]:

a=np.arange(6).reshape(2,3)
print("a:",a)


b=np.arange(7,13).reshape(2,3)
print("b :",b)
np.stack((a,b),axis=2)

a: [[0 1 2]
 [3 4 5]]
b : [[ 7  8  9]
 [10 11 12]]


array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])

Vstack

In [3]:
import numpy as np


a=np.arange(10).reshape(2,5)
print("a:",a)


b=np.arange(7,17).reshape(2,5)
print("b :",b)


print(np.vstack((a,b)))

#Hstack
print(np.hstack((a,b)))

a: [[0 1 2 3 4]
 [5 6 7 8 9]]
b : [[ 7  8  9 10 11]
 [12 13 14 15 16]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
[[ 0  1  2  3  4  7  8  9 10 11]
 [ 5  6  7  8  9 12 13 14 15 16]]


dstack

In [141]:
# using of dstack is axic the matrix
ar=np.dstack((x,y))
print(ar)
print(ar[0,4])

[[[ 1 21]
  [ 3 23]
  [ 5 25]
  [ 7 27]
  [ 9 29]]

 [[11 31]
  [13 33]
  [15 35]
  [17 37]
  [19 39]]]
[ 9 29]


Array Atributes

In [18]:
#SHAPE
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8]])
shape=arr.shape # Find the shape  of the array 
print(shape)

(2, 4)


In [26]:
#NDIM

arr=np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr.ndim)# count the dimension

3


In [27]:
#DTYPE (DATA TYPE)

arr=np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr.dtype) # used to create  data type object

int32


In [34]:
#SIZE

arr=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
print(arr.size) # Find the size of the array

12


Array indexing and slicing

In [38]:
#index
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1])
print(arr[0,2]) #Find the perticular element using index


[5 6 7 8]
3


In [45]:
a=np.arange(10).reshape(2,5)
print(a)
print(a[0:2,1:3]) #subarray

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 2]
 [6 7]]


Reshaping 

In [64]:
a=np.arange(10).reshape(2,5)
print(a)
print(a.reshape(5,2)) # reshape the aray
print(a.flatten())# convert to on edimension
Transpose=a.T
print(Transpose) # convert row to column and column to row

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


Array operation

In [14]:
arr1=np.array([[1,2,3],[4,5,6],[5,2,6]])
print(arr1)
arr2=np.array([[9,8,7],[6,5,4],[2,6,4]])
print(arr2)
print("---------------------------------------")
#1 ADDITION
sum=arr1+arr2
print(sum)
print("---------------------------------------")
#SUBTRACTION
sub=arr1-arr2
print(sub)
print("---------------------------------------")
#MULTIPLICATION
multi=arr1*arr2
print(multi)
print("---------------------------------------")
#DIVISION
Dvision=arr1/arr2
print(Dvision)
print("---------------------------------------")
#FLOAR DIVISION
Div=arr1//arr2
print(Div)
print("---------------------------------------")


[[1 2 3]
 [4 5 6]
 [5 2 6]]
[[9 8 7]
 [6 5 4]
 [2 6 4]]
---------------------------------------
[[10 10 10]
 [10 10 10]
 [ 7  8 10]]
---------------------------------------
[[-8 -6 -4]
 [-2  0  2]
 [ 3 -4  2]]
---------------------------------------
[[ 9 16 21]
 [24 25 24]
 [10 12 24]]
---------------------------------------
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.5        0.33333333 1.5       ]]
---------------------------------------
[[0 0 0]
 [0 1 1]
 [2 0 1]]
---------------------------------------


In [27]:
import numpy as np
import matplotlib.pyplot as plt
arr1=np.array([[1,2,3],[4,5,6],[5,2,6]])
arr2=np.array([[9,8,7],[6,5,4],[2,6,4]])
print(arr1,arr2)
print("---------------------------------------")
# dot product
print("Dot product",np.dot(arr1,arr2))
print("---------------------------------------")
#EXP
print("exp :",np.exp(arr1))
print("---------------------------------------")
print("log :",np.log(arr1))
print("-----------")
result1=np.log2(arr1)
print(result)

print("---------------------------------------")
sin=(np.array((45.,60.,75.,90.,180.))* np.pi / 180.)
print("Sin :",np.sin(sin)) #Print sines of an array of angles given in degrees

[[1 2 3]
 [4 5 6]
 [5 2 6]] [[9 8 7]
 [6 5 4]
 [2 6 4]]
---------------------------------------
Dot product [[27 36 27]
 [78 93 72]
 [69 86 67]]
---------------------------------------
exp : [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]
 [148.4131591    7.3890561  403.42879349]]
---------------------------------------
log : [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.60943791 0.69314718 1.79175947]]
-----------
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]
 [2.32192809 1.         2.5849625 ]]
---------------------------------------
Sin : [7.07106781e-01 8.66025404e-01 9.65925826e-01 1.00000000e+00
 1.22464680e-16]


Statistical function

In [31]:
arr2=np.array([[9,8,7],[6,5,4],[2,6,4]])
print("Mean :",np.mean(arr2)) # Find the mean value of the array
print("Median :",np.median(arr2))#Find the median value of the array
print("Standard deviation :",np.std(arr2))#Find the Std_dev value of the array

Mean : 5.666666666666667
Median : 6.0
Standard deviation : 2.054804667656325


In [41]:
a=np.arange(6).reshape(2,3)
print("a:",a)

b=np.arange(7,13).reshape(2,3)
print("b :",b)

x=np.arange(1,10).reshape(3,3)
print("x :",x)
print("a,b,x Concatenate :",np.concatenate((a,b,x),axis=0))

print("x,b concatenate :",np.concatenate((x,b),axis=0))


a: [[0 1 2]
 [3 4 5]]
b : [[ 7  8  9]
 [10 11 12]]
x : [[1 2 3]
 [4 5 6]
 [7 8 9]]
a,b,x Concatenate : [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
x,b concatenate : [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 7  8  9]
 [10 11 12]]


Missing value

In [59]:
print("IS NAN :" ,np.isnan(1))
print("IS NAN :" ,np.isnan(np.nan))

IS NAN : False
IS NAN : True
