numpy practies

array in numpy all dimentions

In [3]:
import numpy as np

print(np.array(20)) # 0 Dimentation array 

print(np.array([1,2])) # 1 Dimentation array

print(np.array([[[1,2],[3,4]],[[8,6],[9,3]]])) # 2 Dimentation array

20
[1 2]
[[[1 2]
  [3 4]]

 [[8 6]
  [9 3]]]


In [1]:
import numpy as np
print(np.zeros(9))

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
