numpy practies

 Checking the numpy version(np.__version__)

In [1]:
import numpy as np

print(np.__version__)# Checking the numpy version

1.24.3


array in numpy all dimentions (np.array)

In [5]:
import numpy as np

print(np.array(20)) # 0 Dimentation array 

print(np.array([1,2])) # 1 Dimentation array

print(np.array([[[1,2],[3,4]],[[8,6],[9,3]]])) # 2 Dimentation array

print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])) # 3 Dimentation array

print(np.array([[[1,2,3],[4,5,6]]],ndmin=4))  # 4 Dimentation array

print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]],ndmin=5))  # 5 Dimentation array ( creating more than 3D array)

20
[1 2]
[[[1 2]
  [3 4]]

 [[8 6]
  [9 3]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
[[[[1 2 3]
   [4 5 6]]]]
[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [11 12 13]]]]]


check Dimensions (np.ndim),(np.array)

In [8]:
#Check the  Dimentation
a=np.array(23)
b=np.array([[1,2],[3,4]])
d=np.array([[1,2],[3,4]],ndmin=10)
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(d))

0
2
10


Checking Shape of the array

In [15]:
import numpy as np
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([1,2],ndmin=4)
print(arr2.shape)
print(np.shape(arr1))


(1, 1, 1, 2)
(2, 3)


easily create an array filled with 0’s:

In [27]:
import numpy as np

print(np.zeros(9)) # create  an array filled with 0's 

print(np.ones(4)) # create  an array filled with 1's 

print(np.arange(6)) # create an  array with a range of element

print(np.arange(1,10,2)) # create an  array with a range of element

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[0 1 2 3 4 5]
[1 3 5 7 9]
