numpy practies

 Checking the numpy version(np.__version__)

In [74]:
import numpy as np

print(np.__version__)# Checking the numpy version

1.24.3


array in numpy all dimentions (np.array)

In [5]:
import numpy as np

print(np.array(20)) # 0 Dimentation array 

print(np.array([1,2])) # 1 Dimentation array

print(np.array([[[1,2],[3,4]],[[8,6],[9,3]]])) # 2 Dimentation array

print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])) # 3 Dimentation array

print(np.array([[[1,2,3],[4,5,6]]],ndmin=4))  # 4 Dimentation array

print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]],ndmin=5))  # 5 Dimentation array ( creating more than 3D array)

20
[1 2]
[[[1 2]
  [3 4]]

 [[8 6]
  [9 3]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
[[[[1 2 3]
   [4 5 6]]]]
[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [11 12 13]]]]]


check Dimensions (np.ndim),(np.array)

In [8]:
#Check the  Dimentation
a=np.array(23)
b=np.array([[1,2],[3,4]])
d=np.array([[1,2],[3,4]],ndmin=10)
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(d))

0
2
10


Checking Shape of the array

In [1]:
import numpy as np
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([1,2],ndmin=4)
print(arr2.shape)
print(np.shape(arr1))
sh1=np.array([[[1,2,3],[4,5,6]]],ndmin=4)
print(np.shape(sh1))

(1, 1, 1, 2)
(2, 3)
(1, 1, 2, 3)


easily create an array filled with 0’s:

In [11]:
import numpy as np

print(np.zeros(9)) # create  an array filled with 0's 

print(np.zeros([1,10,4])) # create  an array filled with 0's 

print(np.ones([1,10,6])) # create  an array filled with 1's 

print(np.ones(9)) # create  an array filled with 1's 

print(np.arange(6)) # create an  array with a range of element

print(np.arange(1,10,2)) # create an  array with a range of element

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5]
[1 3 5 7 9]


Sorting arrays

In [24]:
import numpy as np

print(np.sort((2,4,1,5,3,6,9,8,6,7,))) # numbers

print(np.sort(("b","a","A","g","y","N","u"))) # alpabets

print(np.sort([[5,2,3],[9,5,2]])) #2 D array



[1 2 3 4 5 6 6 7 8 9]
['A' 'N' 'a' 'b' 'g' 'u' 'y']
[[2 3 5]
 [2 5 9]]


21/06/2023

access an array element by referring to its index number.

In [114]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8])

print(arr[-8:-4])


[1 2 3 4]


In [167]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print("value :",arr[0, 1, 2])

data=np.array([ [[52,65,85],[10,20,30]],[[40,50,60],[70,80,90]] ])
print(data)
print("value :",data[0,0,0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
value : 6
[[[52 65 85]
  [10 20 30]]

 [[40 50 60]
  [70 80 90]]]
value : 52


In [169]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print("value :",arr[1:7:2])

[1 2 3 4 5 6 7 8]
value : [2 4 6]


In [177]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print("value :",arr1[1,0:3])

value : [5 6 7]


In [198]:
arr=np.array([1,2,3,4,5,6,7,4,8,])
x=(np.where(arr%3==1))
z=(np.where(arr%2==0))
print(x)
print(z) # using this condition divisabel by which number divisabel by 2 give the those index number

y=(np.where(arr==4))
print(y)# using this condition give the repeated value of 4




(array([0, 3, 6, 7], dtype=int64),)
(array([1, 3, 5, 7, 8], dtype=int64),)
(array([3, 7], dtype=int64),)


Search sorted array

In [213]:
arr2=np.array([1,2,3,5,6,7])
print(np.searchsorted(arr,4))

print(np.searchsorted([1,2,3,5,6,7],8,side="right"))

print(np.searchsorted([1,2,3,5,6,7],[-2,10,5,-4]))


3
6
[0 6 3 0]


In [244]:
import numpy as np
arr2=np.array([1,2,3,5,4,6,7,8,9,10,11,12])
newarr=arr2.reshape(4,3)
print(newarr)


arr1=np.array([[1,2,3,4],[5,6,7,8]])
x=arr1.reshape(-1)
print(x)

[[ 1  2  3]
 [ 5  4  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6 7 8]
